name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate and Deploy Snake Animation
    runs-on: ubuntu-latest
    steps:
      # Generate Snake SVG
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: aparna22-13
          outputs: |
            dist/github-contribution-grid-snake.svg
          color_snake: "#FF6EC7"
          color_dots: "#00FFE5,#00BFFF,#8A2BE2,#FF69B4,#FFD700"

      # Deploy to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
          keep_history: false
          allow_empty_commit: true
          jekyll: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
