name: 🔄 Update Tech Trends

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  update-trends:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install axios cheerio fs

      - name: Fetch Tech Trends
        run: |
          node .github/scripts/fetch-trends.js

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "⚡ Auto-update tech trends" || echo "No changes to commit"
          git pull --rebase origin main
          git push

